"""Discovery of all stations of the integrated sources within one or more cantons.

Each source class decides itself whether it applies to a canton (attribute `regions`, None = whole
Switzerland) and how its stations are found (classmethod `discover`). National sources use official
station lists (MeteoSwiss), coordinates plus the federal geo service (BAFU, METAR); regional sources
(e.g. the City of Zurich networks) only answer for their canton. A new regional network is added by
writing a Source subclass with `regions` and `discover` and registering it in sources.REGISTRY.
"""
from __future__ import annotations

import logging
from datetime import datetime, timezone

import yaml

from .geo import CANTONS, CantonGeo
from .http import HttpClient
from .model import Clock, utcnow
from .sources import REGISTRY

log = logging.getLogger(__name__)


class DiscoveryContext:
    """Shared services for the discover() methods of the sources: HTTP, geo lookups, clock and a cache
    so that national station lists are downloaded only once for several cantons."""

    def __init__(self, http: HttpClient, clock: Clock = utcnow):
        self.http, self.clock, self.geo = http, clock, CantonGeo(http)
        self.cache: dict = {}

    def cached(self, key, factory):
        if key not in self.cache:
            self.cache[key] = factory()
        return self.cache[key]


class StationDiscovery:
    def __init__(self, http: HttpClient, cantons="ZH", clock: Clock = utcnow, sources=None):
        self.cantons = [c.upper() for c in ([cantons] if isinstance(cantons, str) else cantons)]
        unknown = [c for c in self.cantons if c not in CANTONS]
        if unknown:
            raise ValueError(f"Unknown cantons: {unknown}")
        self.ctx = DiscoveryContext(http, clock)
        self.sources = sources or REGISTRY

    def discover(self, canton: str) -> dict:
        """source name -> list of station entries (each with 'canton')."""
        out = {}
        for name, cls in self.sources.items():
            if cls.regions is not None and canton not in cls.regions:
                continue
            try:
                stations = cls.discover(self.ctx, canton)
            except Exception as e:
                log.warning("%s: discovery for %s failed (%s)", name, canton, e)
                stations = []
            out[name] = [{**s, "canton": canton} for s in stations]
            log.info("%-12s %-2s %3d stations", name, canton, len(stations))
        return out

    def build_config(self, settings: dict | None = None) -> dict:
        cfg: dict = {"settings": settings or {}}
        for canton in self.cantons:
            for name, stations in self.discover(canton).items():
                section = cfg.setdefault(name, {"stations": []})
                key = self.sources[name].key
                known = {str(s[key]) for s in section["stations"]}
                section["stations"] += [s for s in stations if str(s[key]) not in known]
        return {k: v for k, v in cfg.items() if k == "settings" or v["stations"]}

    def write(self, path: str, settings: dict | None = None) -> dict:
        cfg = self.build_config(settings)
        header = (f"# Station list for canton(s) {', '.join(self.cantons)}, generated by 'ledwetter stations' on "
                  f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC.\n"
                  "# Review before use; lat/lon/height are stored as station metadata.\n")
        with open(path, "w", encoding="utf-8") as f:
            f.write(header)
            yaml.safe_dump(cfg, f, allow_unicode=True, sort_keys=False, width=120)
        return cfg
