"""Private weather station at the Greifensee (www.greifenseewetter.ch).

A single hobbyist station, not an official network: no uptime or quality guarantee, and the page
layout could change at any time without notice. Treat it as a convenience source, not a reference.

The site is generated by "Wetterstation Bedien- und Auswertesoftware" (WsWin, Werner Krenn,
pc-wetterstation.de) as a frameset. Two frame pages are used:

- Wetter/aktuell.htm: the current calendar day (local time), at a fine, irregular interval (minutes
  apart around each reading change, widening to roughly hourly overnight).
- Wetter/<year>/w<year>_<ww>.htm: one ISO calendar week, at exactly one row per hour. <year> is the
  ISO week-numbering year of that week (e.g. w2026_01.htm covers 29 Dec 2025 - 4 Jan 2026, because
  ISO week 1 of 2026 starts on that Monday), not necessarily the calendar year of every row in it.

Both pages share most columns (German headers): Datum, Zeit, Luft-Temp., Wasser, Feuchte A.,
Luftdruck, Wind (speed with a Beaufort figure in parentheses), Richtung, [Richtung again photographed
as degrees - daily page only], Windböen (gust, same speed-plus-Beaufort format). The weekly page has
only the one compass-label Richtung column (no degrees); its minute-precise Min-Zeit/Max-Zeit summary
rows show the underlying station logs more often than hourly, so the hourly archive rows are read as
instantaneous snapshots at the hour, not hourly means - supporting time_ref='instant' here too.
Columns are matched by header text (duplicates get a '.1' suffix from the parser), not position, so
that the two layouts are both handled; a row is a data row iff its first cell is a dd.mm.yyyy date.

Open questions, not yet verified against the live site:
  - Whether 'Luftdruck' is station-level (QFE) or reduced to sea level; quantity is left unset so it
    is not merged with other sources' pressure readings until this is confirmed.
  - How far back the weekly archive goes (history_start is a configurable guess, see defaults below);
    missing weeks (before the station existed, or in the future) are skipped with a log message, so
    guessing too early just costs a few harmless 404s.
  - Whether monthly or yearly archive pages also exist (the software is known to support them).
Run 'ledwetter diagnose' after adding this source and check the log for the warnings this module
can emit; update this file once confirmed.
"""
from __future__ import annotations

import io
import logging
import re
from datetime import timedelta
from typing import Iterator, Optional

import pandas as pd
import requests

from ..model import LOCAL_TZ, Period, to_float
from .base import Source

log = logging.getLogger(__name__)

# value, unit, group, aggregation, cross-source quantity (None = not merged with other sources yet)
CATALOG = {
    "air_temperature": ("Lufttemperatur", "°C", "Temperatur", "mean", "air_temperature"),
    "water_temperature": ("Wassertemperatur (Greifensee)", "°C", "Wasser", "mean", "water_temperature"),
    "humidity": ("Relative Luftfeuchte", "%", "Feuchte", "mean", "relative_humidity"),
    "pressure": ("Luftdruck (Korrektur unbekannt)", "hPa", "Druck", "mean", None),
    "wind_speed": ("Windgeschwindigkeit", "km/h", "Wind", "mean", "wind_speed"),
    "wind_force": ("Windstärke", "Bft", "Wind", "mean", None),
    "wind_direction": ("Windrichtung", "°", "Wind", "dir", "wind_direction"),
    "wind_gust": ("Windböen", "km/h", "Wind", "max", "wind_gust"),
    "wind_gust_force": ("Windböen Stärke", "Bft", "Wind", "max", None),
}
# physically implausible values are dropped rather than stored, since this source has no official QA
SANITY_RANGE = {
    "air_temperature": (-30, 45), "water_temperature": (0, 35), "humidity": (0, 100),
    "pressure": (900, 1080), "wind_speed": (0, 150), "wind_gust": (0, 200),
    "wind_direction": (0, 360), "wind_force": (0, 12), "wind_gust_force": (0, 12),
}
# 16-point compass rose in the station's German abbreviations (O = Ost = East); used only on the
# weekly archive, which gives direction as a compass label with no degree column.
COMPASS_DEGREES = {
    "N": 0, "N-NO": 22.5, "NO": 45, "O-NO": 67.5, "O": 90, "O-SO": 112.5, "SO": 135, "S-SO": 157.5,
    "S": 180, "S-SW": 202.5, "SW": 225, "W-SW": 247.5, "W": 270, "W-NW": 292.5, "NW": 315, "N-NW": 337.5,
}
REQUIRED_COLUMNS = {"Datum", "Zeit", "Luft-Temp.", "Wasser", "Feuchte A.", "Luftdruck", "Wind",
                    "Richtung", "Windböen"}
_SPEED_BFT = re.compile(r"([\d.,]+)\s*km/h\s*\((\d+)\s*Bft\)")
_DATE_RE = re.compile(r"^\d{2}\.\d{2}\.\d{4}$")


def _value_and_unit(cell) -> Optional[float]:
    """'22.9 °C' / '1028.4 hPa' / '67 %' -> 22.9 / 1028.4 / 67 (unit discarded, already known)."""
    return to_float(str(cell).split()[0]) if pd.notna(cell) else None


def _speed_and_force(cell) -> tuple:
    """'0.0 km/h (0 Bft)' -> (0.0, 0); unparsable -> (None, None)."""
    m = _SPEED_BFT.search(str(cell))
    return (to_float(m.group(1)), to_float(m.group(2))) if m else (None, None)


def _compass_to_degrees(label, station_id: str) -> Optional[float]:
    deg = COMPASS_DEGREES.get(str(label).strip())
    if deg is None:
        log.warning("greifenseewetter %s: unknown compass label %r, direction dropped", station_id, label)
    return deg


def week_url(base_url: str, year: int, week: int) -> str:
    """URL of the weekly archive page for one ISO (year, week); year is the week-numbering year."""
    return f"{base_url}/{year}/w{year}_{week:02d}.htm"


class GreifenseeWetter(Source):
    name = "greifenseewetter"
    key = "id"
    regions = ("ZH",)
    CATALOG = CATALOG
    defaults = {
        "base_url": "https://www.greifenseewetter.ch/Wetter", "today_page": "aktuell.htm",
        "lookback_hours": 30,            # how far back 'today' alone can reach
        "history_start": "2020-01-01",   # earliest week to attempt; unconfirmed, see module docstring
    }

    @classmethod
    def discover(cls, ctx, canton: str) -> list:
        return [{"id": "greifensee", "name": "Greifensee (private, greifenseewetter.ch)"}]

    def history_start(self, st: Optional[dict] = None):
        return pd.Timestamp(self.cfg["history_start"], tz="UTC").to_pydatetime()

    # ---------------------------------------------------------------- Fetching
    def fetch_station(self, st: dict, period: Period) -> Iterator[pd.DataFrame]:
        today_local = pd.Timestamp(self.clock()).tz_convert(LOCAL_TZ).date()
        start_local = pd.Timestamp(period.start).tz_convert(LOCAL_TZ).date()
        end_local = pd.Timestamp(period.end).tz_convert(LOCAL_TZ).date()

        seen_weeks = set()
        d = start_local
        while d <= end_local:
            key = d.isocalendar()[:2]  # (iso_year, iso_week)
            if key not in seen_weeks:
                seen_weeks.add(key)
                yield from self._fetch_table(week_url(self.cfg["base_url"], *key), st, "week")
            d += timedelta(days=1)

        if end_local >= today_local:
            url = f"{self.cfg['base_url']}/{self.cfg['today_page']}"
            yield from self._fetch_table(url, st, "today")

    def _fetch_table(self, url: str, st: dict, label: str) -> Iterator[pd.DataFrame]:
        log.info("greifenseewetter %s: loading %s (%s)", st["id"], url.rsplit("/", 1)[-1], label)
        try:
            html = self.http.get(url).content.decode("utf-8", errors="replace")
        except requests.HTTPError as e:
            log.info("greifenseewetter %s: %s not available (%s)", st["id"], url.rsplit("/", 1)[-1], e)
            return
        yield from self.parse(html, st)

    def parse(self, html: str, st: dict) -> Iterator[pd.DataFrame]:
        try:
            tables = pd.read_html(io.StringIO(html))
        except (ValueError, ImportError):
            # ValueError: lxml found no <table> at all. ImportError: lxml found no table either and
            # pandas' fallback parser (html5lib) isn't installed - same practical meaning here.
            log.warning("greifenseewetter %s: no table found on the page", st["id"])
            return
        df = max(tables, key=len)  # the readings table is the largest one on the page
        if df.empty or not REQUIRED_COLUMNS <= set(df.columns):
            log.warning("greifenseewetter %s: table layout looks different than expected (columns: %s)",
                        st["id"], list(df.columns))
            return

        date_col = df.iloc[:, 0].astype(str).str.strip()
        rows = df[date_col.str.match(_DATE_RE, na=False)].copy()
        if rows.empty:
            log.warning("greifenseewetter %s: no data rows recognised (summary-row filter matched "
                        "everything)", st["id"])
            return

        t = pd.to_datetime(rows["Datum"] + " " + rows["Zeit"].astype(str), format="%d.%m.%Y %H:%M",
                           errors="coerce")
        t = t.dt.tz_localize(LOCAL_TZ, ambiguous="NaT", nonexistent="NaT").dt.tz_convert("UTC")
        wind, force = zip(*rows["Wind"].map(_speed_and_force)) if len(rows) else ((), ())
        gust, gust_force = zip(*rows["Windböen"].map(_speed_and_force)) if len(rows) else ((), ())
        if "Richtung.1" in rows.columns:
            direction = rows["Richtung.1"].map(_value_and_unit)
        else:
            direction = rows["Richtung"].map(lambda c: _compass_to_degrees(c, st["id"]))
        values = {
            "air_temperature": rows["Luft-Temp."].map(_value_and_unit),
            "water_temperature": rows["Wasser"].map(_value_and_unit),
            "humidity": rows["Feuchte A."].map(_value_and_unit),
            "pressure": rows["Luftdruck"].map(_value_and_unit),
            "wind_speed": pd.Series(wind, index=rows.index),
            "wind_force": pd.Series(force, index=rows.index),
            "wind_direction": direction,
            "wind_gust": pd.Series(gust, index=rows.index),
            "wind_gust_force": pd.Series(gust_force, index=rows.index),
        }
        for param, series in values.items():
            lo, hi = SANITY_RANGE[param]
            v = pd.to_numeric(series, errors="coerce")
            bad = v.notna() & ~v.between(lo, hi)
            if bad.any():
                log.warning("greifenseewetter %s: %d implausible %s values dropped (outside %s-%s)",
                            st["id"], int(bad.sum()), param, lo, hi)
                v = v.where(~bad)
            info = self.CATALOG[param]
            yield self.frame(t, v, st["id"], st["name"], param, info[1], "instant", None)
